[package]
name = "nertsal-bot"
version = "0.1.0"
authors = ["Kudasov Alexander <sasha.kudasov04@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twitch-irc = "0.2.1"
futures = "0.3.6"
tokio = "0.2.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.7.3"
async-trait = "0.1.41"
